DATA Wen;
SET SAS.Wen;
RUN;


/* Logistic Regresson */

DATA NEWWEN;
SET WEN;
IF DMA=220 THEN DMA220 = 1; ELSE DMA220 = 0;
IF DMA=320 THEN DMA320 = 1; ELSE DMA320 = 0;
IF DMA=970 THEN DMA970 = 1; ELSE DMA970 = 0;
IF DMA=90 THEN DMA90 = 1; ELSE DMA90 = 0;
RUN;


PROC LOGISTIC DATA = NEWWEN DESCENDING;
MODEL REDEEM_WELCOME = NUM_TXNS AVG_PRICE TENURE _DM _EM _SMS DMA;
RUN;


/* Clustering */

PROC STANDARD DATA = Wen MEAN = 0 STD = 1 Out=zwen;
RUN;


PROC FASTCLUS DATA = zwen
MAXCLUSTERS = 4  OUT = clus;
VAR HH_INCOME AVG_PRICE TENURE _DM;
RUN;


DATA WendyClust;
MERGE
  NEWWEN
  clus (KEEP = cluster obs=3443);
RUN;


PROC PRINT DATA = WendyCLust (obs = 30);
RUN;

/* Descriptive statistics based on clusters */

PROC SQL;
   SELECT DISTINCT (DMA) AS AVG
   FROM Wen;
QUIT;


PROC CORR DATA = Wen;
VAR DYPT_PCT_BR DYPT_PCT_LU DYPT_PCT_AF DYPT_PCT_DINNER DYPT_PCT_EVEN DYPT_PCT_NITE;
RUN;


PROC FREQ DATA = WendyCLust;
TABLE CLUSTER;
RUN;


PROC SUMMARY DATA = wendyCLust;
WHERE CLUSTER = 1;
VAR HH_INCOME SIZE_HH _DM _EM _SMS TENURE AVG_PRICE TOT_SALES NUM_TXNS DMA BAKR_QTY BEVRG_QTY CHICK_QTY FRST_QTY HAMBR_QTY KID_QTY
MEALDEAL_QTY NUM_EARN_REDEEM OTHER_PCT REDEEM_WELCOME SALAD_PCT SALD_QTY CHICKN_PCT BAKERY_PCT DYPT_PCT_AF DYPT_PCT_BR DYPT_PCT_DINNER
DYPT_PCT_EVEN DYPT_PCT_LU DYPT_PCT_NITE FRSTY_PCT HAMBRGR_PCT KID_PCT MEALDEAL_PCT TOT_REWARDS_EARN TOT_UNITS VALU_QTY _AVG_TB_TRANS;
output out=meancluster1 mean=;
RUN;


PROC PRINT DATA = meancluster1;
RUN;


PROC SUMMARY DATA = wendyCLust;
WHERE CLUSTER = 2;
VAR HH_INCOME SIZE_HH _DM _EM _SMS TENURE AVG_PRICE TOT_SALES NUM_TXNS DMA BAKR_QTY BEVRG_QTY CHICK_QTY FRST_QTY HAMBR_QTY KID_QTY
MEALDEAL_QTY NUM_EARN_REDEEM OTHER_PCT REDEEM_WELCOME SALAD_PCT SALD_QTY CHICKN_PCT BAKERY_PCT DYPT_PCT_AF DYPT_PCT_BR DYPT_PCT_DINNER
DYPT_PCT_EVEN DYPT_PCT_LU DYPT_PCT_NITE FRSTY_PCT HAMBRGR_PCT KID_PCT MEALDEAL_PCT TOT_REWARDS_EARN TOT_UNITS VALU_QTY _AVG_TB_TRANS;
output out=meancluster2 mean=;
RUN;


PROC PRINT DATA = meancluster2;
RUN;


PROC SUMMARY DATA = wendyCLust;
WHERE CLUSTER = 3;
VAR HH_INCOME SIZE_HH _DM _EM _SMS TENURE AVG_PRICE TOT_SALES NUM_TXNS DMA BAKR_QTY BEVRG_QTY CHICK_QTY FRST_QTY HAMBR_QTY KID_QTY
MEALDEAL_QTY NUM_EARN_REDEEM OTHER_PCT REDEEM_WELCOME SALAD_PCT SALD_QTY CHICKN_PCT BAKERY_PCT DYPT_PCT_AF DYPT_PCT_BR DYPT_PCT_DINNER
DYPT_PCT_EVEN DYPT_PCT_LU DYPT_PCT_NITE FRSTY_PCT HAMBRGR_PCT KID_PCT MEALDEAL_PCT TOT_REWARDS_EARN TOT_UNITS VALU_QTY _AVG_TB_TRANS;
output out=meancluster3 mean=;
RUN;


PROC PRINT DATA = meancluster3;
RUN;


PROC SUMMARY DATA = wendyCLust;
WHERE CLUSTER = 4;
VAR HH_INCOME SIZE_HH _DM _EM _SMS TENURE AVG_PRICE TOT_SALES NUM_TXNS DMA BAKR_QTY BEVRG_QTY CHICK_QTY FRST_QTY HAMBR_QTY KID_QTY
MEALDEAL_QTY NUM_EARN_REDEEM OTHER_PCT REDEEM_WELCOME SALAD_PCT SALD_QTY CHICKN_PCT BAKERY_PCT DYPT_PCT_AF DYPT_PCT_BR DYPT_PCT_DINNER
DYPT_PCT_EVEN DYPT_PCT_LU DYPT_PCT_NITE FRSTY_PCT HAMBRGR_PCT KID_PCT MEALDEAL_PCT TOT_REWARDS_EARN TOT_UNITS VALU_QTY _AVG_TB_TRANS;
output out=meancluster4 mean=;
RUN;


PROC PRINT DATA = meancluster4;
RUN;


PROC SUMMARY DATA = wendyCLust;
WHERE CLUSTER = 1;
VAR  CHICK_QTY FRST_QTY FRY_QTY HAMBR_QTY KID_QTY MEALDEAL_QTY SALD_QTY BEVRG_QTY BAKR_QTY VALU_QTY _DM _EM _SMS TOT_SALES TOT_UNITS
TOT_REWARDS_EARN SIZE_HH REDEEM_WELCOME NUM_TXNS NUM_EARN_REDEEM HH_INCOME;
OUTPUT OUT = sumcluster1 sum=;
RUN;

PROC PRINT DATA = sumcluster1;
RUN;


PROC SUMMARY DATA = wendyCLust;
WHERE CLUSTER = 2;
VAR  CHICK_QTY FRST_QTY FRY_QTY HAMBR_QTY KID_QTY MEALDEAL_QTY SALD_QTY BEVRG_QTY BAKR_QTY VALU_QTY _DM _EM _SMS TOT_SALES TOT_UNITS
TOT_REWARDS_EARN SIZE_HH REDEEM_WELCOME NUM_TXNS NUM_EARN_REDEEM HH_INCOME;
OUTPUT OUT = sumcluster2 sum=;
RUN;

PROC PRINT DATA = sumcluster2;
RUN;

PROC SUMMARY DATA = wendyCLust;
WHERE CLUSTER = 3;
VAR  CHICK_QTY FRST_QTY FRY_QTY HAMBR_QTY KID_QTY MEALDEAL_QTY SALD_QTY BEVRG_QTY BAKR_QTY VALU_QTY _DM _EM _SMS TOT_SALES TOT_UNITS
TOT_REWARDS_EARN SIZE_HH REDEEM_WELCOME NUM_TXNS NUM_EARN_REDEEM HH_INCOME;
OUTPUT OUT = sumcluster3 sum=;
RUN;

PROC PRINT DATA = sumcluster3;
RUN;

PROC SUMMARY DATA = wendyCLust;
WHERE CLUSTER = 4;
VAR  CHICK_QTY FRST_QTY FRY_QTY HAMBR_QTY KID_QTY MEALDEAL_QTY SALD_QTY BEVRG_QTY BAKR_QTY VALU_QTY _DM _EM _SMS TOT_SALES TOT_UNITS
TOT_REWARDS_EARN SIZE_HH REDEEM_WELCOME NUM_TXNS NUM_EARN_REDEEM HH_INCOME;
OUTPUT OUT = sumcluster4 sum=;
RUN;

PROC PRINT DATA = sumcluster4;
RUN;


/* Calculating Price Elasticity */

PROC REG DATA = WendyClust;
WHERE CLUSTER = 4;
model TOT_UNITS = AVG_PRICE;
RUN;



/* Regression */

PROC REG DATA = WendyClust;
MODEL TOT_SALES = NUM_TXNS CHICK_QTY BAKR_QTY FRST_QTY FRY_QTY HAMBR_QTY KID_QTY MEALDEAL_QTY SALD_QTY BEVRG_QTY
DYPT_PCT_EVEN DYPT_PCT_BR DYPT_PCT_DINNER DYPT_PCT_LU DYPT_PCT_NITE ;
RUN;
